#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Protocolos (interfaces) para el algoritmo de flujo máximo."""

from typing import Protocol, List


class FlowNetwork(Protocol):
    """
    Interfaz que debe cumplir una red de flujo para Edmonds-Karp.
    Permite sustituir la implementación (MatrizCap) sin cambiar BFS ni CaminoAumentante.
    """

    def agregar_lado(self, x: int, y: int, cap: int) -> None: ...
    def capacidad_total(self, x: int, y: int) -> int: ...
    def flujo_actual(self, x: int, y: int) -> int: ...
    def capacidad_actual(self, x: int, y: int) -> int: ...
    def gamma_mas(self, x: int) -> List[int]: ...
    def gamma_menos(self, x: int) -> List[int]: ...
    def no_esta_saturado(self, x: int, y: int) -> bool: ...
    def tiene_flujo(self, x: int, y: int) -> bool: ...
    def flujo_desde_fuente(self) -> int: ...
    def flujo_forward(self, x: int, y: int, flujo: float) -> None: ...
    def flujo_backward(self, x: int, y: int, flujo: float) -> None: ...
    def capacidad_corte(self, corte: List[int]) -> int: ...
